### PR TITLE
fix & optimize eide icon

### PR DESCRIPTION
**Pull request by Crystal-RainSlide**
- set `<circle>`'s `cx` from `80.285` to `80`;
- merge paths with same color (`#878787`);
- remove unnessary rect / path;
- `icon.png` is re-exported from Inkscape, then changed color mode to
  `8-bit gray+alpha` & compressed losslessly with `ect -9 -strip`.

Note that, since the original icon is using a 1.5px width stroke,
every edge is 0.75px wider than their real size.
The inner white rect is also affected and I'm using a 1.5px position drift
to mimic the original visual.

### CODE REVIEW

**Comment by github0null** [comment]
Were there any potential problems with the previous images ?

What did these changes improve ?

I don't know much about this aspect of image processing.

**Comment by Crystal-RainSlide** [comment]
Just some perfection and correction, let me explain by comparing my change to `icon.svg`:

- > ``` diff
  > -<path fill="none" d="M0 0h160v160H0z"/>
  > ```
  Invisible `<path>` which did nothing at all, removed.

- > ``` diff
  > -<circle cy="80" cx="80.285" fill="#fff" r="80"/>
  > +<circle cx="80" cy="80" r="80" fill="#fff"/>
  > ```
  Original image's white circle is not perfectly centered, but off to right by 0.285px, fixed.

  One may confirm this tiny position drifting error by compare the mirrored and non-mirrored version of the original icon.

  This change corrected visual, which means it affected the PNG, so I re-exported & compressed `icon.png`.

- > ``` diff
  > -<path stroke-width="1.5" stroke="#878787" fill="#878787" d="M47 47h66v66H47z"/><path stroke-width="1.5" stroke="#fff" fill="#fff" d="M68 68h24v24H68z"/><path stroke-width="1.5" stroke="#878787" fill="#878787" d="M53 113h12v15H53zM74 113h12v15H74zM95 113h12v15H95zM113 53h15v12h-15zM113 95h15v12h-15zM113 74h15v12h-15zM53 32h12v15H53zM74 32h12v15H74zM95 32h12v15H95zM32 53h15v12H32zM32 74h15v12H32zM32 95h15v12H32z"/>
  > +<path fill="#878787" stroke="#878787" stroke-width="1.5" d="M47 47h6V32h12v15h9V32h12v15h9V32h12v15h6v6h15v12h-15v9h15v12h-15v9h15v12h-15v6h-6v15H95v-15h-9v15H74v-15h-9v15H53v-15h-6v-6H32V95h15v-9H32V74h15v-9H32V53h15zm19.5 19.5v27h27v-27z"/>
  > ```
  The optimization, merged 3 paths into 1 path, which should be the shortest currect solution for the dark inner shape on this icon.

  The white inner rect, `<path stroke-width="1.5" stroke="#fff" fill="#fff" d="M68 68h24v24H68z"/>`, is replaced with a real square hole (`m19.5 19.5v27h27v-27z`) in the new path, and thus no longer needed and removed.

**Comment by github0null** [comment]
ok

**Comment by github0null** [comment]
And you need to merge to `dev` branch

The `master` is readonly

**Comment by Crystal-RainSlide** [comment]
New PR which commits to `dev` branch: https://github.com/github0null/eide/pull/244

**Pull request closed without merging**
